### PR TITLE
Feature/redmine 3 support

### PR DESCRIPTION
**Pull request by s2chmich**
No problem, here you go! :) Sorry for the delay.

### CODE REVIEW

**Comment by jperelli** [comment]
Thank you for sharing! I updated the main readme to reflect the current redmine3 support. I stated that the 1.x redmine support is dropped. I suspect but really don't know if the changes you made break redmine 1.x, so I wrote that the 1.x support is Unknown.

**Comment by jperelli** [comment]
If you could test if 1.x keeps working with this changes applied, and let me know, it would be awesome, but don't bother if there is too much trouble.

**Comment by s2chmich** [comment]
I'm going to focus on another task now, which is why I won't be able to test my changes for Redmine 1.X, too. That version of Redmine is rather outdated in my opinion and it has already dropped out of the installation requirements overview on the respective wiki page. Thank you, too, for adapting the readme! I didn't think of that.

**Comment by jperelli** [comment]
Ok, no problem. Thanks!

**Pull request merged**
