### PR TITLE
Adding issue category to period tasks

### PR DESCRIPTION
**Pull request by ossrjus**
Hi

I have amended the period task plugin to accept and use the issue category.

As I'm not a ruby developer, I'd be glad to get any input from you guys as to how to improve my commit so you can merge it in if the purpose fits your roadmap.

Thanks and cheers
-Urs

### CODE REVIEW

**Comment by jperelli** [comment]
Could you please pull from master and update this pull request, so it can be mergable and tested by travis?

**Comment by ossrjus** [comment]
Will do once back from vacation. Thanks and cheers, Urs 


Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: Julián Perelli <notifications@github.com> 
Datum: 05.10.2015  20:57  (GMT+01:00) 
An: jperelli/Redmine-Periodic-Task <Redmine-Periodic-Task@noreply.github.com> 
Cc: Urs <urs.joss@gmx.ch> 
Betreff: Re: [Redmine-Periodic-Task] Adding issue category to period tasks
  (#31) 

Could you please pull from master and update this pull request, so it can be mergable and tested by travis?

**Comment by ossrjus** [comment]
Done

**Comment by jperelli** [comment]
Great, I'll bump the version after merging.
Thank you!

**Pull request merged**
